// Cadenas de interfaz del móvil, ES/EN. Espejo fiel de apps/web/messages/*.json
// (mismas palabras y tono), recortadas a lo que el móvil realmente muestra hoy.
//
// Uso: const { t } = useT(); t("settings.theme")
// Plurales/interpolación simple: t("onboarding.progress", { n, total }).

export const STRINGS = {
  es: {
    app: {
      name: "Aluna",
      tagline: "Tu mapa de autoconocimiento",
    },
    nav: {
      hoy: "Hoy",
      numeros: "Números",
      ajustes: "Ajustes",
    },
    hoy: {
      greetingDawn: "Buena madrugada",
      greetingMorning: "Buenos días",
      greetingAfternoon: "Buenas tardes",
      greetingNight: "Buenas noches",
      traveler: "viajera",
      dayNumberTitle: "Numerología de hoy",
      dayNumberMonth: "Mes",
      dayNumberYear: "Año",
      lifePathEyebrow: "Camino de Vida",
      lifePathGo: "Ver mi mapa numérico  →",
      soon: "Próximamente",
      climateTitle: "Tu Clima",
      climateBody: "El clima energético de tus áreas de vida, día a día.",
      cartaTitle: "Carta Astral",
      cartaBody: "Tu rueda natal y sus interpretaciones, calculadas con precisión.",
      readingsTitle: "Lecturas de Aluna",
      readingsBody: "Lecturas evolutivas tejidas para ti, con la voz interior de Aluna.",
    },
    numerology: {
      title: "Numerología",
      subtitle: "Tu mapa numérico",
      emptyMap: "Aún no hay un mapa que leer.",
      master: "★ Número maestro",
      pro: "Modo Pro",
      tapHint: "Toca un número para ver su esencia y cómo se calcula.",
      karmicLessons: "Lecciones kármicas",
      debts: "Deudas kármicas",
      none: "Ninguna",
      inclusion: "Tabla de inclusión",
      hiddenPassion: "Pasión oculta",
      pinnacles: "Pináculos",
      challenges: "Desafíos",
      cycles: "Ciclos del momento",
      personalYear: "Año personal",
      personalMonth: "Mes personal",
      personalDay: "Día personal",
    },
    reading: {
      master: "★ Número maestro",
      yourCalc: "Tu cálculo",
      tierEssence: "Esencia",
      tierDeep: "Profunda",
      tierComplete: "Completa",
      gatedNote: "Las lecturas más extensas las teje Aluna cuando despierte su voz interior.",
      flowH: "✦  Energía fluida",
      shadowH: "◐  Energía no fluida",
      practiceH: "☾  Tu práctica",
      proseSoon: "La lectura evolutiva de este número llega pronto.",
    },
    onboarding: {
      back: "Atrás",
      next: "Continuar",
      create: "Tejer mi mapa",
      creating: "Tejiendo tu mapa…",
      nameEyebrow: "Empecemos",
      nameTitle: "¿Cómo te llamas?",
      namePlaceholder: "Tu nombre completo",
      dateEyebrow: "Tu llegada",
      dateTitle: "¿Qué día naciste?",
      datePick: "Elige tu fecha",
      timeEyebrow: "El instante",
      timeTitle: "¿A qué hora naciste?",
      timePick: "Elige la hora",
      timeUnknown: "No sé mi hora",
      timeHint: "La hora afina tu carta; puedes dejarla para después.",
      placeEyebrow: "El cielo de ese día",
      placeTitle: "¿Dónde naciste?",
      placePlaceholder: "Tu ciudad de nacimiento",
      genderEyebrow: "Para hablarte bien",
      genderTitle: "¿Cómo te nombramos?",
      genderHint: "Define el género con que te hablan tus lecturas.",
    },
    settings: {
      title: "Ajustes",
      profile: "Tu perfil",
      birth: "Nacimiento",
      time: "Hora",
      timeUnset: "Sin definir",
      place: "Lugar",
      gender: "Género",
      appearance: "Apariencia",
      theme: "Tema",
      lightMode: "Modo de luz",
      light: "Claro",
      dark: "Oscuro",
      auto: "Auto",
      language: "Idioma",
      systems: "Sistemas",
      sysNumerology: "Numerología",
      sysCarta: "Carta Astral",
      sysBazi: "Ba Zi / Saju",
      sysReadings: "Lecturas de Aluna (IA)",
      available: "disponible",
      soon: "pronto",
      reset: "Tejer otro mapa",
      resetConfirmTitle: "¿Tejer otro mapa?",
      resetConfirmBody:
        "Esto borra el perfil actual de este dispositivo y vuelve al inicio ceremonial.",
      resetCancel: "Cancelar",
      resetConfirm: "Empezar de nuevo",
      footNote: "Aluna · para jugar y explorar",
      offline: "Todo se calcula en tu dispositivo. Sin conexión a un servidor.",
    },
    gender: {
      feminine: "Femenino",
      masculine: "Masculino",
      neutral: "Neutro",
    },
  },

  en: {
    app: {
      name: "Aluna",
      tagline: "Your map of self-knowledge",
    },
    nav: {
      hoy: "Today",
      numeros: "Numbers",
      ajustes: "Settings",
    },
    hoy: {
      greetingDawn: "Good early morning",
      greetingMorning: "Good morning",
      greetingAfternoon: "Good afternoon",
      greetingNight: "Good evening",
      traveler: "traveler",
      dayNumberTitle: "Today's numerology",
      dayNumberMonth: "Month",
      dayNumberYear: "Year",
      lifePathEyebrow: "Life Path",
      lifePathGo: "See my numeric map  →",
      soon: "Coming soon",
      climateTitle: "Your Weather",
      climateBody: "The energetic weather of your life areas, day by day.",
      cartaTitle: "Birth Chart",
      cartaBody: "Your natal wheel and its interpretations, calculated with precision.",
      readingsTitle: "Aluna's Readings",
      readingsBody: "Evolutionary readings woven for you, in Aluna's inner voice.",
    },
    numerology: {
      title: "Numerology",
      subtitle: "Your numeric map",
      emptyMap: "There's no map to read yet.",
      master: "★ Master number",
      pro: "Pro Mode",
      tapHint: "Tap a number to see its essence and how it's calculated.",
      karmicLessons: "Karmic lessons",
      debts: "Karmic debts",
      none: "None",
      inclusion: "Inclusion table",
      hiddenPassion: "Hidden passion",
      pinnacles: "Pinnacles",
      challenges: "Challenges",
      cycles: "Cycles of the moment",
      personalYear: "Personal year",
      personalMonth: "Personal month",
      personalDay: "Personal day",
    },
    reading: {
      master: "★ Master number",
      yourCalc: "Your calculation",
      tierEssence: "Essence",
      tierDeep: "Deep",
      tierComplete: "Complete",
      gatedNote: "The longer readings are woven by Aluna when she finds her inner voice.",
      flowH: "✦  Flowing energy",
      shadowH: "◐  Blocked energy",
      practiceH: "☾  Your practice",
      proseSoon: "The evolutionary reading of this number is coming soon.",
    },
    onboarding: {
      back: "Back",
      next: "Continue",
      create: "Weave my map",
      creating: "Weaving your map…",
      nameEyebrow: "Let's begin",
      nameTitle: "What's your name?",
      namePlaceholder: "Your full name",
      dateEyebrow: "Your arrival",
      dateTitle: "What day were you born?",
      datePick: "Pick your date",
      timeEyebrow: "The moment",
      timeTitle: "What time were you born?",
      timePick: "Pick the time",
      timeUnknown: "I don't know my time",
      timeHint: "The time sharpens your chart; you can leave it for later.",
      placeEyebrow: "The sky that day",
      placeTitle: "Where were you born?",
      placePlaceholder: "Your city of birth",
      genderEyebrow: "So we speak to you well",
      genderTitle: "How shall we address you?",
      genderHint: "Sets the grammatical gender your readings use.",
    },
    settings: {
      title: "Settings",
      profile: "Your profile",
      birth: "Birth",
      time: "Time",
      timeUnset: "Not set",
      place: "Place",
      gender: "Gender",
      appearance: "Appearance",
      theme: "Theme",
      lightMode: "Light mode",
      light: "Light",
      dark: "Dark",
      auto: "Auto",
      language: "Language",
      systems: "Systems",
      sysNumerology: "Numerology",
      sysCarta: "Birth Chart",
      sysBazi: "Ba Zi / Saju",
      sysReadings: "Aluna's Readings (AI)",
      available: "available",
      soon: "soon",
      reset: "Weave another map",
      resetConfirmTitle: "Weave another map?",
      resetConfirmBody:
        "This clears the current profile on this device and returns to the ceremonial start.",
      resetCancel: "Cancel",
      resetConfirm: "Start over",
      footNote: "Aluna · to play and explore",
      offline: "Everything is computed on your device. No server connection.",
    },
    gender: {
      feminine: "Feminine",
      masculine: "Masculine",
      neutral: "Neutral",
    },
  },
};

/**
 * Forma del diccionario con hojas ensanchadas a `string`: así ES y EN son
 * estructuralmente compatibles (sin esto, `as const` los volvería literales
 * distintos y la unión rompería el lookup). Derivada del árbol ES.
 */
export type Strings = {
  [K in keyof (typeof STRINGS)["es"]]: {
    [J in keyof (typeof STRINGS)["es"][K]]: string;
  };
};
