// Cadenas de interfaz del móvil, ES/EN. Espejo fiel de apps/web/messages/*.json
// (mismas palabras y tono), recortadas a lo que el móvil realmente muestra hoy.
//
// Uso: const { t } = useT(); t("settings.theme")
// Plurales/interpolación simple: t("onboarding.progress", { n, total }).

export const STRINGS = {
  es: {
    app: {
      name: "Aluna",
      tagline: "Tu mapa de autoconocimiento",
    },
    auth: {
      login: "Entrar",
      signup: "Crear cuenta",
      email: "Correo",
      password: "Contraseña",
      logout: "Salir",
      noAccount: "¿No tienes cuenta?",
      haveAccount: "¿Ya tienes cuenta?",
      errEmail: "Correo inválido",
      errPassword: "La contraseña debe tener al menos 8 caracteres",
      errAuth: "Correo o contraseña incorrectos",
      confirmEmail: "Revisa tu correo para confirmar tu cuenta",
      creating: "Creando cuenta…",
      loggingIn: "Entrando…",
      forgotPassword: "¿Olvidaste tu contraseña?",
      forgotTitle: "Encontremos el camino de vuelta",
      forgotBody: "Dinos tu correo y te enviamos un enlace para elegir una contraseña nueva.",
      sendResetLink: "Enviar enlace",
      resetLinkSent: "Si ese correo tiene cuenta, el enlace ya va en camino. Revisa tu bandeja.",
      resetTitle: "Elige una nueva contraseña",
      newPassword: "Nueva contraseña",
      confirmPassword: "Confirmar contraseña",
      updatePassword: "Actualizar contraseña",
      resetSuccess: "Tu contraseña quedó actualizada. Entra con tu nueva llave.",
      errResetLink: "Este enlace es inválido o ya venció. Pide uno nuevo.",
      errPasswordMatch: "Las contraseñas no coinciden",
      backToLogin: "Volver a iniciar sesión",
    },
    nav: {
      hoy: "Hoy",
      astros: "Astros",
      pilares: "Pilares",
      numeros: "Números",
      ajustes: "Ajustes",
    },
    universo: {
      eyebrow: "Tu universo",
      compatTitle: "Compatibilidad",
      compatBody: "El cielo entre dos",
      informesTitle: "Informes",
      informesBody: "Tu carta en profundidad",
      preguntarTitle: "Pregúntale a Aluna",
      preguntarBody: "Te respondo desde tu cielo",
    },
    compat: {
      eyebrow: "Compatibilidad",
      title: "El cielo entre dos personas",
      subtitle: "¿Con quién quieres mirar el cielo?",
      you: "Tú",
      withWhom: "Y…",
      needSecondTitle: "Añade otra persona para comparar",
      needSecondBody: "Todavía no tienes un segundo perfil guardado. Por ahora, crea a la otra persona desde la web — pronto podrás hacerlo aquí también.",
      cta: "Ver el vínculo",
      loading: "Leyendo el cielo entre ustedes…",
      error: "No se pudo leer el vínculo. Inténtalo de nuevo.",
      of100: "de 100",
      framing: "La sinastría no dice si encajan, sino dónde se reflejan. Un mapa del terreno que comparten, no un veredicto.",
      themeAttraction: "Atracción",
      themeCommunication: "Comunicación",
      themeHarmony: "Armonía",
      themeGrowth: "Crecimiento",
      growthHint: "fricción fértil",
      noDrivers: "Sin contactos marcados en este tema.",
    },
    informe: {
      title: "Informes evolutivos",
      subtitle: "Lecturas largas nacidas de tu cielo, escritas para releer.",
      natalTitle: "Carta natal",
      natalEyebrow: "Informe natal",
      solarEyebrow: "Revolución Solar {year}",
      solarTitle: "Tu año que empieza",
      none: "Todavía no generaste este informe.",
      generate: "Generar",
      generating: "Generando tu informe… toca Actualizar en un momento.",
      update: "Actualizar",
      error: "Algo salió mal.",
      retry: "Reintentar",
      read: "Leer",
      regenerate: "Regenerar",
      generatedWith: "Generado con {model}",
      dormantTitle: "El oráculo aún duerme",
      dormantBody: "Los informes evolutivos se encienden cuando conectes la voz de IA de Aluna.",
      needProfileTitle: "Crea tu perfil primero",
      needProfileBody: "Necesitas un perfil con fecha y lugar de nacimiento para generar tus informes.",
      paywallTitle: "Los informes evolutivos son parte de",
      paywallBrand: "Aluna Plus",
      paywallBody: "Tu carta natal y tu Revolución Solar completas, capítulo a capítulo. Escritas desde tu cielo, para releer toda la vida.",
      paywallCta: "Ver planes",
      sectionIntro: "Introducción",
      sectionOutro: "Cierre",
      solarEssay: "Ensayo del año",
      solarMantra: "Mantra",
      solarWhy: "Por qué",
      solarInvitation: "Invitación",
    },
    preguntar: {
      greeting: "Aquí estoy. Pregúntame lo que sea — de tu día, de tu carta, de lo que te inquieta esta noche.",
      placeholder: "Escribe tu pregunta…",
      send: "Enviar",
      thinking: "Aluna está sintiendo tu pregunta…",
      error: "Algo se nubló. Inténtalo de nuevo.",
      dormantTitle: "El oráculo aún duerme",
      dormantBody: "El chat con Aluna se enciende cuando conectes su voz de IA. Mientras, tu carta y tus números ya te hablan en sus secciones.",
      needProfileBody: "Necesitas un perfil con fecha y lugar de nacimiento para conversar con Aluna.",
      suggestion1: "¿Por qué siento tanto?",
      suggestion2: "¿Cómo amo yo?",
      suggestion3: "¿Qué me pide este año?",
    },
    hoy: {
      traveler: "viajera",
      calm: "Cielo en calma, sin tránsitos marcados.",
      periodToday: "Hoy",
      periodWeek: "Semana",
      periodMonth: "Mes",
      periodYear: "Año",
      areaLove: "Amor",
      areaMoney: "Dinero",
      areaWork: "Trabajo",
      areaHealth: "Salud",
      areaMood: "Ánimo",
      areaLuck: "Suerte",
      toneHigh: "fluida",
      toneMixed: "mixta",
      toneLow: "en reto",
      // Hub de clima astrológico (mockup 01-hoy-hub.html, R4/Task 3b) —
      // reemplaza el hub numerológico anterior.
      title: "Tu clima del alma, {name}",
      energyEyebrow: "Tu energía de hoy",
      moonRoman: "LUNA EN {sign} ✦ ENERGÍA DE {energy}",
      voiceUnavailable: "El cielo guarda silencio por ahora.",
      moonUnavailable: "Tu clima lunar no cargó todavía.",
      energyUnavailable: "Tu energía de hoy no cargó todavía.",
      eventUnavailable: "El evento lunar no cargó todavía.",
      eventNone: "Cielo en calma: sin eventos lunares en el horizonte cercano.",
      moonEventNewLead: "Luna nueva {when}",
      moonEventNewTail: "buen día para sembrar intención",
      moonEventFullLead: "Luna llena {when}",
      moonEventFullTail: "buen día para soltar lo que sobra",
      whenToday: "hoy",
      whenTomorrow: "mañana",
      whenInDays: "en {n} días",
    },
    numerology: {
      title: "Numerología",
      headTitle: "Tus números, {name}",
      emptyMap: "Aún no hay un mapa que leer.",
      master: "★ Número maestro",
      pro: "Modo Pro",
      ctaFull: "Ver la lectura completa de tus números ›",
      birthdayTitle: "Día de nacimiento",
      karmicLessons: "Lecciones kármicas",
      debts: "Deudas kármicas",
      none: "Ninguna",
      inclusion: "Tabla de inclusión",
      hiddenPassion: "Pasión oculta",
      pinnacles: "Pináculos",
      challenges: "Desafíos",
      cycles: "Ciclos del momento",
      personalYear: "Año personal",
      personalMonth: "Mes personal",
      personalDay: "Día personal",
    },
    carta: {
      title: "Carta Astral",
      ascendant: "Ascendente",
      house: "Casa",
      elements: "Elementos",
      modalities: "Modalidades",
      dominant: "Dominante",
      pro: "Modo Pro",
      positions: "Posiciones",
      distribution: "Distribución",
      aspectsTitle: "Aspectos",
      patterns: "Patrones",
      noPatterns: "Sin patrones mayores",
      solarNotice: "Sin hora de nacimiento: carta solar. Casas y Ascendente son aproximados.",
      tapHint: "Toca un planeta para ver su detalle",
      applying: "Aplicativo",
      separating: "Separativo",
      orb: "Orbe",
      ut: "TU",
      julianDay: "Día juliano",
      loadingChart: "Trazando tu cielo…",
      errorChart: "No se pudo trazar la carta. Inténtalo de nuevo.",
      emptyMap: "Aún no hay un cielo que leer.",
      kindNatal: "Natal",
      kindTransits: "Tu Clima",
      kindSolarReturn: "Rev. Solar",
      kindProgressed: "Progresiones",
      kindSolarReturnHint: "Tu carta del año, desde tu último cumpleaños.",
      kindProgressedHint: "Tu carta avanzada: cómo madura tu cielo con los años.",
      weatherTitle: "Tu clima de hoy",
      yourPossessive: "tu",
      readingEssence: "Esencia",
      readingDeep: "Profunda",
      readingComplete: "Completa",
      readingFlowH: "✦  Su don",
      readingShadowH: "◐  Su sombra",
      readingWeaving: "Aluna está tejiendo tu lectura…",
      readingGated: "Las lecturas más extensas las teje Aluna cuando despierte su voz interior.",
      readingError: "No se pudo tejer la lectura. Inténtalo de nuevo.",
      houses: "Casas",
      zodiacT: "Tropical",
      zodiacS: "Sideral",
      headEyebrow: "Tu carta",
      headTitle: "Carta natal",
      segNatal: "Natal",
      segTransits: "Tránsitos",
      zodiac: "Zodiaco",
      moreCharts: "Otras cartas",
    },
    pilares: {
      headEyebrow: "Ba Zi · Cuatro Pilares",
      headTitle: "Tus cuatro pilares",
      balance: "Balance de elementos",
      noTime: "Sin hora de nacimiento: el pilar de hora queda oculto.",
      loading: "Calculando tus pilares…",
      error: "No se pudieron calcular los pilares. Inténtalo de nuevo.",
      emptyMap: "Aún no hay pilares que leer.",
      modePro: "Modo Pro",
      modeProHint: "Diez Dioses y troncos ocultos relativos a tu Maestro del Día.",
      hiddenStems: "Troncos ocultos",
      dayMasterHanzi: "日主",
      scriptBazi: "Ba Zi",
      scriptSaju: "Saju",
      nayinTitle: "Na Yin · elementos melódicos",
      strengthTitle: "Fuerza del Maestro del Día",
      strengthMethod: "Método: mando del mes + raíces y apoyos ponderados",
      seasonState: "Estado estacional",
      favorTitle: "Elementos favorables",
      avoidTitle: "A moderar",
      balancedNote: "Tu Maestro del Día está en equilibrio: ninguna familia de elementos domina; observa el matiz de cada década.",
      luckTitle: "Pilares de Suerte",
      luckStart: "Primer pilar a los {years} años y {months} meses",
      luckForward: "Ciclo ascendente",
      luckBackward: "Ciclo descendente",
      luckNeutralNote: "La tradición deriva la dirección del sexo de nacimiento; te mostramos ambas.",
      luckNoTimeNote: "Sin hora exacta, la edad de inicio tiene una imprecisión de ±2 meses.",
      annualTitle: "Años de flujo",
      annualJanFebNote: "Si naciste en enero–febrero, el pilar del año cambia en Lichun (~4 feb), no el 1 de enero.",
      currentDecade: "Década actual",
      age: "años",
      stagesTitle: "Las 12 etapas",
      interactionsTitle: "Interacciones",
      interactionsEmpty: "Sin interacciones mayores entre tus pilares: un mapa sereno.",
      starsTitle: "Estrellas simbólicas",
      threePillarsNote: "Sin hora de nacimiento el cálculo usa 3 pilares; el pilar de hora y sus estrellas se omiten.",
    },
    horoscopo: {
      title: "Horóscopo",
      // Copy propio de la cabecera compacta (T7): distinto del switch "Astros"
      // de arriba, que ya usa `title` ("Horóscopo") como label del chip — evita
      // repetir el mismo texto dos veces en ~60px de alto. Mismo criterio que
      // carta.headEyebrow/headTitle (T4), que tampoco repiten el label de su chip.
      headEyebrow: "Tu horóscopo",
      headTitle: "Leído para tu signo",
      tabWestern: "Occidental",
      tabEastern: "Oriental",
      easternSoon: "La lectura oriental (animales y pilares) llega pronto.",
      signAria: "Elige un signo",
      skyTitle: "El cielo del periodo",
      periodAria: "Elige el periodo",
      areasTitle: "Tus áreas",
      aspectsTitle: "Aspectos por signo",
      hitsTitle: "Esto toca tu carta",
      proseTitle: "Tu lectura",
      pro: "Modo Pro",
      proPositions: "Tránsitos por casa solar",
      proEvents: "Eventos con hora exacta",
      proMethod: "Casas solares whole-sign desde {sign}. Aspectos por signo (whole-sign). Muestras del periodo a mediodía local. Zona horaria: {tz}.",
      loading: "Leyendo el cielo…",
      error: "El cielo no respondió. Intenta de nuevo.",
      newMoon: "Luna Nueva",
      fullMoon: "Luna Llena",
      eclipseSolar: "eclipse solar",
      eclipseLunar: "eclipse lunar",
      stationRetro: "{body} estaciona retrógrado",
      stationDirect: "{body} retoma marcha directa",
      ingress: "{body} entra en {sign}",
      houseShort: "casa {n}",
      exactOn: "exacto: {date}",
      noEvents: "Sin eventos mayores en este periodo: cielo de fondo estable.",
    },
    reading: {
      master: "★ Número maestro",
      yourCalc: "Tu cálculo",
      tierEssence: "Esencia",
      tierDeep: "Profunda",
      tierComplete: "Completa",
      gatedNote: "Las lecturas más extensas las teje Aluna cuando despierte su voz interior.",
      flowH: "✦  Energía fluida",
      shadowH: "◐  Energía no fluida",
      practiceH: "☾  Tu práctica",
      proseSoon: "La lectura evolutiva de este número llega pronto.",
    },
    onboarding: {
      back: "Atrás",
      next: "Continuar",
      create: "Tejer mi mapa",
      creating: "Tejiendo tu mapa…",
      createError: "No se pudo tejer tu mapa. Revisa tu conexión e inténtalo de nuevo.",
      nameEyebrow: "Empecemos",
      nameTitle: "¿Cómo te llamas?",
      namePlaceholder: "Tu nombre completo",
      dateEyebrow: "Tu llegada",
      dateTitle: "¿Qué día naciste?",
      datePick: "Elige tu fecha",
      timeEyebrow: "El instante",
      timeTitle: "¿A qué hora naciste?",
      timePick: "Elige la hora",
      timeUnknown: "No sé mi hora",
      timeHint: "La hora afina tu carta; puedes dejarla para después.",
      placeEyebrow: "El cielo de ese día",
      placeTitle: "¿Dónde naciste?",
      placePlaceholder: "Tu ciudad de nacimiento",
      genderEyebrow: "Para hablarte bien",
      genderTitle: "¿Cómo te nombramos?",
      genderHint: "Define el género con que te hablan tus lecturas.",
      intentGoalsEyebrow: "Tu intención",
      intentGoalsTitle: "¿Qué te trae a Aluna?",
      intentGoalsHint: "Elige lo que resuene. Puedes cambiar de rumbo cuando quieras.",
      intentGoalSelf: "Conocerme en profundidad",
      intentGoalBonds: "Mis vínculos",
      intentGoalPurpose: "Mi propósito",
      intentGoalFuture: "Prepararme para lo que viene",
      intentGoalSpirituality: "Explorar la espiritualidad",
      intentGoalOthers: "Entender a los demás",
      intentGoalDecisions: "Guía para decidir",
      intentGoalNotePlaceholder: "¿Algo más? (opcional)",
      intentAffirmEyebrow: "Con Aluna",
      intentAffirmTitle: "Este será tu camino",
      intentAffirmSelf: "Vas a mirarte con honestidad y ternura (svadhyaya).",
      intentAffirmBonds: "Vas a entender tus vínculos desde el alma, no desde el miedo.",
      intentAffirmPurpose: "Vas a escuchar tu dharma: lo que viniste a hacer.",
      intentAffirmFuture: "Vas a caminar hacia lo que viene con los ojos abiertos.",
      intentAffirmSpirituality: "Vas a explorar lo sagrado a tu propio ritmo.",
      intentAffirmOthers: "Vas a ver a los demás con más compasión y claridad.",
      intentAffirmDecisions: "Vas a decidir desde tu centro, no desde el ruido.",
      intentFocusEyebrow: "Tu foco",
      intentFocusTitle: "¿Dónde quieres más luz ahora?",
      intentFocusHint: "Tu panel de energía pondrá estas áreas primero.",
      intentFocusLove: "Amor",
      intentFocusMoney: "Dinero",
      intentFocusWork: "Trabajo",
      intentFocusHealth: "Salud",
      intentFocusMood: "Ánimo",
      intentFocusLuck: "Suerte",
      intentRelEyebrow: "Tu corazón",
      intentRelTitle: "¿Cómo está tu corazón hoy?",
      intentRelSingle: "En soltería",
      intentRelPartnered: "En pareja",
      intentRelSituationship: "Sin etiquetas",
      intentRelEngaged: "En compromiso",
      intentRelMarried: "En matrimonio",
      intentRelSeparated: "En separación",
      intentRelDivorced: "Tras un divorcio",
      intentRelWidowed: "En viudez",
      intentRelComplicated: "Es complicado",
      intentRelPrivate: "Prefiero no decirlo",
      intentHeartNotePlaceholder: "¿Algo que quieras compartir? (opcional)",
      intentSkip: "Omitir",
      intentCuspHint: "El límite exacto lo dirá tu carta",
    },
    settings: {
      title: "Ajustes",
      profile: "Tu perfil",
      birth: "Nacimiento",
      time: "Hora",
      timeUnset: "Sin definir",
      place: "Lugar",
      gender: "Género",
      appearance: "Apariencia",
      theme: "Tema",
      lightMode: "Modo de luz",
      light: "Claro",
      dark: "Oscuro",
      auto: "Auto",
      palette: "Color",
      paletteGold: "Dorado",
      paletteColorful: "Colorido",
      language: "Idioma",
      systems: "Sistemas",
      sysNumerology: "Numerología",
      sysCarta: "Carta Astral",
      sysBazi: "Ba Zi / Saju",
      sysReadings: "Lecturas de Aluna (IA)",
      available: "disponible",
      soon: "pronto",
      reset: "Tejer otro mapa",
      resetConfirmTitle: "¿Tejer otro mapa?",
      resetConfirmBody:
        "Esto borra el perfil actual de este dispositivo y vuelve al inicio ceremonial.",
      resetCancel: "Cancelar",
      resetConfirm: "Empezar de nuevo",
      logoutConfirmTitle: "¿Cerrar sesión?",
      logoutConfirmBody: "Vuelves a la pantalla de acceso; tus datos siguen a salvo en tu cuenta.",
      footNote: "Aluna · para jugar y explorar",
      offline: "Numerología se calcula en tu dispositivo; la Carta usa el servidor de Aluna (necesita conexión).",
      intentAI: "Personalizar lecturas con mis intenciones",
      intentAIHint: "Solo si respondiste el cuestionario. Apagado, Aluna lee tu carta sin ese contexto.",
      intentAIOn: "Encendido",
      intentAIOff: "Apagado",
      planWebNote: "Gestiona tu plan desde la versión web.",
      account: "Cuenta",
      email: "Correo",
      userId: "ID de usuario",
      loginMethod: "Método de acceso",
      loginEmail: "Correo y contraseña",
      copyId: "Copiar",
      copied: "¡Copiado!",
      help: "Ayuda y soporte",
      askAluna: "Pregúntale a Aluna",
      followUs: "Síguenos",
      legal: "Legal",
    },
    gender: {
      feminine: "Femenino",
      masculine: "Masculino",
      neutral: "Neutro",
    },
    billing: {
      title: "Tu plan",
      freeBody: "Numerología y Carta completas, gratis para siempre.",
      upsell: "Hazte Plus en aluna.app",
      planTrialing: "En prueba gratis",
      planActive: "Aluna Plus",
      planPastDue: "Pago pendiente",
      manageNote: "Gestiona tu suscripción en aluna.app",
      renewsOn: "Se renueva el {date}",
      trialEndsOn: "La prueba termina el {date}",
    },
    legal: {
      back: "Volver",
      updated: "Actualizado {date}",
      draftNote: "Borrador en revisión — este documento puede cambiar antes del lanzamiento.",
    },
  },

  en: {
    app: {
      name: "Aluna",
      tagline: "Your map of self-knowledge",
    },
    auth: {
      login: "Log in",
      signup: "Sign up",
      email: "Email",
      password: "Password",
      logout: "Log out",
      noAccount: "No account yet?",
      haveAccount: "Already have an account?",
      errEmail: "Invalid email",
      errPassword: "Password must be at least 8 characters",
      errAuth: "Incorrect email or password",
      confirmEmail: "Check your email to confirm your account",
      creating: "Creating account…",
      loggingIn: "Logging in…",
      forgotPassword: "Forgot your password?",
      forgotTitle: "Let's find your way back",
      forgotBody: "Tell us your email and we'll send you a link to set a new password.",
      sendResetLink: "Send reset link",
      resetLinkSent: "If that email has an account, a link is on its way. Check your inbox.",
      resetTitle: "Set a new password",
      newPassword: "New password",
      confirmPassword: "Confirm password",
      updatePassword: "Update password",
      resetSuccess: "Your password is updated. Log in with your new key.",
      errResetLink: "This link is invalid or has expired. Ask for a new one.",
      errPasswordMatch: "Passwords don't match",
      backToLogin: "Back to log in",
    },
    nav: {
      hoy: "Today",
      astros: "Astros",
      pilares: "Pillars",
      numeros: "Numbers",
      ajustes: "Settings",
    },
    universo: {
      eyebrow: "Your universe",
      compatTitle: "Compatibility",
      compatBody: "The sky between two",
      informesTitle: "Reports",
      informesBody: "Your chart in depth",
      preguntarTitle: "Ask Aluna",
      preguntarBody: "I answer from your sky",
    },
    compat: {
      eyebrow: "Compatibility",
      title: "The sky between two people",
      subtitle: "Who do you want to look at the sky with?",
      you: "You",
      withWhom: "And…",
      needSecondTitle: "Add another person to compare",
      needSecondBody: "You don't have a second saved profile yet. For now, create the other person from the web — soon you'll be able to do it here too.",
      cta: "See the bond",
      loading: "Reading the sky between you…",
      error: "Couldn't read the bond. Try again.",
      of100: "of 100",
      framing: "Synastry doesn't say whether you fit, but where you mirror each other. A map of the terrain you share, not a verdict.",
      themeAttraction: "Attraction",
      themeCommunication: "Communication",
      themeHarmony: "Harmony",
      themeGrowth: "Growth",
      growthHint: "fertile friction",
      noDrivers: "No contacts marked in this theme.",
    },
    informe: {
      title: "Evolutionary reports",
      subtitle: "Long readings born from your sky, written to revisit.",
      natalTitle: "Birth chart",
      natalEyebrow: "Natal report",
      solarEyebrow: "Solar Return {year}",
      solarTitle: "Your year ahead",
      none: "You haven't generated this report yet.",
      generate: "Generate",
      generating: "Generating your report… tap Refresh in a moment.",
      update: "Refresh",
      error: "Something went wrong.",
      retry: "Retry",
      read: "Read",
      regenerate: "Regenerate",
      generatedWith: "Generated with {model}",
      dormantTitle: "The oracle still sleeps",
      dormantBody: "Evolutionary reports light up when you connect Aluna's AI voice.",
      needProfileTitle: "Create your profile first",
      needProfileBody: "You need a profile with birth date and place to generate your reports.",
      paywallTitle: "Evolutionary reports are part of",
      paywallBrand: "Aluna Plus",
      paywallBody: "Your birth chart and Solar Return, complete, chapter by chapter. Written from your sky, to reread for life.",
      paywallCta: "See plans",
      sectionIntro: "Introduction",
      sectionOutro: "Closing",
      solarEssay: "Essay of the year",
      solarMantra: "Mantra",
      solarWhy: "Why",
      solarInvitation: "Invitation",
    },
    preguntar: {
      greeting: "Here I am. Ask me anything — about your day, your chart, or what's on your mind tonight.",
      placeholder: "Type your question…",
      send: "Send",
      thinking: "Aluna is sensing your question…",
      error: "Something clouded over. Try again.",
      dormantTitle: "The oracle still sleeps",
      dormantBody: "The chat with Aluna lights up when you connect her AI voice. Meanwhile, your chart and numbers already speak to you in their sections.",
      needProfileBody: "You need a profile with birth date and place to talk with Aluna.",
      suggestion1: "Why do I feel so much?",
      suggestion2: "How do I love?",
      suggestion3: "What does this year ask of me?",
    },
    hoy: {
      traveler: "traveler",
      calm: "Calm skies, no marked transits.",
      periodToday: "Today",
      periodWeek: "Week",
      periodMonth: "Month",
      periodYear: "Year",
      areaLove: "Love",
      areaMoney: "Money",
      areaWork: "Work",
      areaHealth: "Health",
      areaMood: "Mood",
      areaLuck: "Luck",
      toneHigh: "flowing",
      toneMixed: "mixed",
      toneLow: "challenged",
      title: "Your soul's weather, {name}",
      energyEyebrow: "Your energy today",
      moonRoman: "MOON IN {sign} ✦ ENERGY OF {energy}",
      voiceUnavailable: "The sky is quiet for now.",
      moonUnavailable: "Your lunar weather hasn't loaded yet.",
      energyUnavailable: "Today's energy hasn't loaded yet.",
      eventUnavailable: "The lunar event hasn't loaded yet.",
      eventNone: "Calm skies: no lunar events on the near horizon.",
      moonEventNewLead: "New moon {when}",
      moonEventNewTail: "a good day to plant intention",
      moonEventFullLead: "Full moon {when}",
      moonEventFullTail: "a good day to release what's excess",
      whenToday: "today",
      whenTomorrow: "tomorrow",
      whenInDays: "in {n} days",
    },
    numerology: {
      title: "Numerology",
      headTitle: "Your numbers, {name}",
      emptyMap: "There's no map to read yet.",
      master: "★ Master number",
      pro: "Pro Mode",
      ctaFull: "See the full reading of your numbers ›",
      birthdayTitle: "Birthday number",
      karmicLessons: "Karmic lessons",
      debts: "Karmic debts",
      none: "None",
      inclusion: "Inclusion table",
      hiddenPassion: "Hidden passion",
      pinnacles: "Pinnacles",
      challenges: "Challenges",
      cycles: "Cycles of the moment",
      personalYear: "Personal year",
      personalMonth: "Personal month",
      personalDay: "Personal day",
    },
    carta: {
      title: "Birth Chart",
      ascendant: "Ascendant",
      house: "House",
      elements: "Elements",
      modalities: "Modalities",
      dominant: "Dominant",
      pro: "Pro Mode",
      positions: "Positions",
      distribution: "Distribution",
      aspectsTitle: "Aspects",
      patterns: "Patterns",
      noPatterns: "No major patterns",
      solarNotice: "No birth time: solar chart. Houses and Ascendant are approximate.",
      tapHint: "Tap a planet to see its detail",
      applying: "Applying",
      separating: "Separating",
      orb: "Orb",
      ut: "UT",
      julianDay: "Julian day",
      loadingChart: "Charting your sky…",
      errorChart: "Couldn't chart it. Please try again.",
      emptyMap: "There's no sky to read yet.",
      kindNatal: "Natal",
      kindTransits: "Your Weather",
      kindSolarReturn: "Solar Return",
      kindProgressed: "Progressions",
      kindSolarReturnHint: "Your chart for the year, from your last birthday.",
      kindProgressedHint: "Your advanced chart: how your sky matures over the years.",
      weatherTitle: "Today's weather",
      yourPossessive: "your",
      readingEssence: "Essence",
      readingDeep: "Deep",
      readingComplete: "Complete",
      readingFlowH: "✦  Its gift",
      readingShadowH: "◐  Its shadow",
      readingWeaving: "Aluna is weaving your reading…",
      readingGated: "The longer readings are woven by Aluna when she finds her inner voice.",
      readingError: "Couldn't weave the reading. Please try again.",
      houses: "Houses",
      zodiacT: "Tropical",
      zodiacS: "Sidereal",
      headEyebrow: "Your chart",
      headTitle: "Birth chart",
      segNatal: "Natal",
      segTransits: "Transits",
      zodiac: "Zodiac",
      moreCharts: "More charts",
    },
    pilares: {
      headEyebrow: "Ba Zi · Four Pillars",
      headTitle: "Your four pillars",
      balance: "Element balance",
      noTime: "No birth time: the hour pillar is hidden.",
      loading: "Calculating your pillars…",
      error: "Couldn't calculate the pillars. Please try again.",
      emptyMap: "There are no pillars to read yet.",
      modePro: "Pro Mode",
      modeProHint: "Ten Gods and hidden stems relative to your Day Master.",
      hiddenStems: "Hidden stems",
      dayMasterHanzi: "日主",
      scriptBazi: "Ba Zi",
      scriptSaju: "Saju",
      nayinTitle: "Na Yin · melodic elements",
      strengthTitle: "Day Master strength",
      strengthMethod: "Method: month command + weighted roots and support",
      seasonState: "Seasonal state",
      favorTitle: "Favorable elements",
      avoidTitle: "To moderate",
      balancedNote: "Your Day Master is balanced: no element family dominates; watch the nuance of each decade.",
      luckTitle: "Luck Pillars",
      luckStart: "First pillar at {years} years and {months} months",
      luckForward: "Ascending cycle",
      luckBackward: "Descending cycle",
      luckNeutralNote: "Tradition derives the direction from birth sex; we show you both.",
      luckNoTimeNote: "Without an exact time, the starting age has ±2 months of imprecision.",
      annualTitle: "Flow years",
      annualJanFebNote: "If you were born in January–February, the year pillar changes at Lichun (~Feb 4), not January 1.",
      currentDecade: "Current decade",
      age: "yrs",
      stagesTitle: "The 12 stages",
      interactionsTitle: "Interactions",
      interactionsEmpty: "No major interactions between your pillars: a serene map.",
      starsTitle: "Symbolic stars",
      threePillarsNote: "Without a birth time the calculation uses 3 pillars; the hour pillar and its stars are omitted.",
    },
    horoscopo: {
      title: "Horoscope",
      headEyebrow: "Your horoscope",
      headTitle: "Read for your sign",
      tabWestern: "Western",
      tabEastern: "Eastern",
      easternSoon: "The Eastern reading (animals and pillars) is coming soon.",
      signAria: "Choose a sign",
      skyTitle: "The sky of the period",
      periodAria: "Choose the period",
      areasTitle: "Your areas",
      aspectsTitle: "Aspects by sign",
      hitsTitle: "Touching your chart",
      proseTitle: "Your reading",
      pro: "Pro Mode",
      proPositions: "Transits by solar house",
      proEvents: "Events with exact time",
      proMethod: "Whole-sign solar houses from {sign}. Sign-to-sign aspects. Period sampled at local noon. Time zone: {tz}.",
      loading: "Reading the sky…",
      error: "The sky did not answer. Try again.",
      newMoon: "New Moon",
      fullMoon: "Full Moon",
      eclipseSolar: "solar eclipse",
      eclipseLunar: "lunar eclipse",
      stationRetro: "{body} stations retrograde",
      stationDirect: "{body} stations direct",
      ingress: "{body} enters {sign}",
      houseShort: "house {n}",
      exactOn: "exact: {date}",
      noEvents: "No major events this period: a steady background sky.",
    },
    reading: {
      master: "★ Master number",
      yourCalc: "Your calculation",
      tierEssence: "Essence",
      tierDeep: "Deep",
      tierComplete: "Complete",
      gatedNote: "The longer readings are woven by Aluna when she finds her inner voice.",
      flowH: "✦  Flowing energy",
      shadowH: "◐  Blocked energy",
      practiceH: "☾  Your practice",
      proseSoon: "The evolutionary reading of this number is coming soon.",
    },
    onboarding: {
      back: "Back",
      next: "Continue",
      create: "Weave my map",
      creating: "Weaving your map…",
      createError: "Couldn't weave your map. Check your connection and try again.",
      nameEyebrow: "Let's begin",
      nameTitle: "What's your name?",
      namePlaceholder: "Your full name",
      dateEyebrow: "Your arrival",
      dateTitle: "What day were you born?",
      datePick: "Pick your date",
      timeEyebrow: "The moment",
      timeTitle: "What time were you born?",
      timePick: "Pick the time",
      timeUnknown: "I don't know my time",
      timeHint: "The time sharpens your chart; you can leave it for later.",
      placeEyebrow: "The sky that day",
      placeTitle: "Where were you born?",
      placePlaceholder: "Your city of birth",
      genderEyebrow: "So we speak to you well",
      genderTitle: "How shall we address you?",
      genderHint: "Sets the grammatical gender your readings use.",
      intentGoalsEyebrow: "Your intention",
      intentGoalsTitle: "What brings you to Aluna?",
      intentGoalsHint: "Choose what resonates. You can change course anytime.",
      intentGoalSelf: "Know myself deeply",
      intentGoalBonds: "My bonds",
      intentGoalPurpose: "My purpose",
      intentGoalFuture: "Prepare for what's coming",
      intentGoalSpirituality: "Explore spirituality",
      intentGoalOthers: "Understand others",
      intentGoalDecisions: "Guidance to decide",
      intentGoalNotePlaceholder: "Anything else? (optional)",
      intentAffirmEyebrow: "With Aluna",
      intentAffirmTitle: "This will be your path",
      intentAffirmSelf: "You'll look at yourself with honesty and tenderness (svadhyaya).",
      intentAffirmBonds: "You'll understand your bonds from the soul, not from fear.",
      intentAffirmPurpose: "You'll listen to your dharma: what you came here to do.",
      intentAffirmFuture: "You'll walk toward what's coming with open eyes.",
      intentAffirmSpirituality: "You'll explore the sacred at your own pace.",
      intentAffirmOthers: "You'll see others with more compassion and clarity.",
      intentAffirmDecisions: "You'll decide from your center, not from the noise.",
      intentFocusEyebrow: "Your focus",
      intentFocusTitle: "Where do you want more light now?",
      intentFocusHint: "Your energy panel will put these areas first.",
      intentFocusLove: "Love",
      intentFocusMoney: "Money",
      intentFocusWork: "Work",
      intentFocusHealth: "Health",
      intentFocusMood: "Mood",
      intentFocusLuck: "Luck",
      intentRelEyebrow: "Your heart",
      intentRelTitle: "How is your heart today?",
      intentRelSingle: "Single",
      intentRelPartnered: "In a relationship",
      intentRelSituationship: "Situationship",
      intentRelEngaged: "Engaged",
      intentRelMarried: "Married",
      intentRelSeparated: "Separated",
      intentRelDivorced: "Divorced",
      intentRelWidowed: "Widowed",
      intentRelComplicated: "It's complicated",
      intentRelPrivate: "I'd rather not say",
      intentHeartNotePlaceholder: "Anything you'd like to share? (optional)",
      intentSkip: "Skip",
      intentCuspHint: "Your chart will tell the exact boundary",
    },
    settings: {
      title: "Settings",
      profile: "Your profile",
      birth: "Birth",
      time: "Time",
      timeUnset: "Not set",
      place: "Place",
      gender: "Gender",
      appearance: "Appearance",
      theme: "Theme",
      lightMode: "Light mode",
      light: "Light",
      dark: "Dark",
      auto: "Auto",
      palette: "Color",
      paletteGold: "Gold",
      paletteColorful: "Colorful",
      language: "Language",
      systems: "Systems",
      sysNumerology: "Numerology",
      sysCarta: "Birth Chart",
      sysBazi: "Ba Zi / Saju",
      sysReadings: "Aluna's Readings (AI)",
      available: "available",
      soon: "soon",
      reset: "Weave another map",
      resetConfirmTitle: "Weave another map?",
      resetConfirmBody:
        "This clears the current profile on this device and returns to the ceremonial start.",
      resetCancel: "Cancel",
      resetConfirm: "Start over",
      logoutConfirmTitle: "Log out?",
      logoutConfirmBody: "You'll return to the sign-in screen; your data stays safe in your account.",
      footNote: "Aluna · to play and explore",
      offline: "Numerology is computed on your device; the Chart uses Aluna's server (needs a connection).",
      intentAI: "Personalize readings with my intentions",
      intentAIHint: "Only if you answered the questionnaire. Off, Aluna reads your chart without that context.",
      intentAIOn: "On",
      intentAIOff: "Off",
      planWebNote: "Manage your plan from the web version.",
      account: "Account",
      email: "Email",
      userId: "User ID",
      loginMethod: "Login method",
      loginEmail: "Email and password",
      copyId: "Copy",
      copied: "Copied!",
      help: "Help & support",
      askAluna: "Ask Aluna",
      followUs: "Follow us",
      legal: "Legal",
    },
    gender: {
      feminine: "Feminine",
      masculine: "Masculine",
      neutral: "Neutral",
    },
    billing: {
      title: "Your plan",
      freeBody: "Full Numerology and Birth Chart, free forever.",
      upsell: "Go Plus at aluna.app",
      planTrialing: "Free trial",
      planActive: "Aluna Plus",
      planPastDue: "Payment overdue",
      manageNote: "Manage your subscription at aluna.app",
      renewsOn: "Renews on {date}",
      trialEndsOn: "Trial ends on {date}",
    },
    legal: {
      back: "Back",
      updated: "Updated {date}",
      draftNote: "Draft under review — this document may change before launch.",
    },
  },
};

/**
 * Forma del diccionario con hojas ensanchadas a `string`: así ES y EN son
 * estructuralmente compatibles (sin esto, `as const` los volvería literales
 * distintos y la unión rompería el lookup). Derivada del árbol ES.
 */
export type Strings = {
  [K in keyof (typeof STRINGS)["es"]]: {
    [J in keyof (typeof STRINGS)["es"][K]]: string;
  };
};
